In [1]:
import numpy as np

np.matrix这个函数已经标记启用了，提示使用数组代替。

## 矩阵的相加
和数组没有广播的相加是一样的，两个矩阵可以相加减，必须shape一样。

In [2]:
a = np.full((3,3), 1)
b = np.full((3,3), 2)

In [3]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [4]:
#可以用数组的加减代替矩阵的加减
a + b

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [5]:
a - b

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

**这个是数据的加法(广播)**，矩阵中没有这个概念，但是可以利用这个做一些计算。

In [6]:
a + 10

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

## 矩阵的数乘

In [7]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
a * 10

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [9]:
# 除法不就是乘法吗
a / 10

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

## 矩阵与相乘

m x n 的矩阵可以和 n x d 的举证相乘，得到m x d 的矩阵。

In [10]:
a = np.full((3,3), 1)
b = np.full((3,2), 2)

In [11]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

**dot和matmul都可以计算矩阵的乘法**。这两个也是有区别的，可以查看注释，不过在矩阵的乘法的概念上的计算都是一样的。

In [13]:
np.dot(a , b)

array([[6, 6],
       [6, 6],
       [6, 6]])

In [14]:
np.matmul(a, b)

array([[6, 6],
       [6, 6],
       [6, 6]])

## 矩阵的转置

**A.T**和**np.transpose(A)**都可以得到A的转置矩阵

In [15]:
A = np.arange(1, 13).reshape(4,3)
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
A.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [17]:
np.transpose(A)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

## 矩阵和向量相乘

这个也是十分常用的，线性方程组的表示等。

In [18]:
a = np.full((2,3), 1)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
# 这个可以看成向量
b = np.array([1, 2, 3]) 
b

array([1, 2, 3])

In [20]:
b.shape

(3,)

In [21]:
# 这个乘出来是一维的数组，相当于向量
np.dot(a, b)

array([6, 6])

In [22]:
c = b.reshape(3,1)
c

array([[1],
       [2],
       [3]])

In [23]:
c.shape

(3, 1)

In [24]:
# 这个乘出来是二维的数组，相当于矩阵
np.dot(a, c)

array([[6],
       [6]])