In [1]:
import numpy as np

In [2]:
# delimiter : str, optional.The default is whitespace.
datas = np.loadtxt("data.txt", delimiter=",", dtype="float64")

In [3]:
x = datas[:,:-1]
y = datas[:, -1].reshape(-1,1)

In [4]:
from sklearn import linear_model #线性回归的模型
from sklearn.preprocessing import StandardScaler    #引入归一化的包

In [5]:
# 归一化操作
scaler = StandardScaler()   
scaler.fit(x)
x_train = scaler.transform(x)
x_test = scaler.transform(np.array([[2104,3]]))

In [6]:
x_train

array([[ 1.31415422e-01, -2.26093368e-01],
       [-5.09640698e-01, -2.26093368e-01],
       [ 5.07908699e-01, -2.26093368e-01],
       [-7.43677059e-01, -1.55439190e+00],
       [ 1.27107075e+00,  1.10220517e+00],
       [-1.99450507e-02,  1.10220517e+00],
       [-5.93588523e-01, -2.26093368e-01],
       [-7.29685755e-01, -2.26093368e-01],
       [-7.89466782e-01, -2.26093368e-01],
       [-6.44465993e-01, -2.26093368e-01],
       [-7.71822042e-02,  1.10220517e+00],
       [-8.65999486e-04, -2.26093368e-01],
       [-1.40779041e-01, -2.26093368e-01],
       [ 3.15099326e+00,  2.43050370e+00],
       [-9.31923697e-01, -2.26093368e-01],
       [ 3.80715024e-01,  1.10220517e+00],
       [-8.65782986e-01, -1.55439190e+00],
       [-9.72625673e-01, -2.26093368e-01],
       [ 7.73743478e-01,  1.10220517e+00],
       [ 1.31050078e+00,  1.10220517e+00],
       [-2.97227261e-01, -2.26093368e-01],
       [-1.43322915e-01, -1.55439190e+00],
       [-5.04552951e-01, -2.26093368e-01],
       [-4.

In [7]:
x_train.mean(axis=0)

array([-9.44870659e-18,  2.48028548e-16])

In [8]:
# 线性模型拟合
model = linear_model.LinearRegression()
model.fit(x_train, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
#预测结果
result = model.predict(x_test)
print(model.coef_)       # Coefficient of the features 决策函数中的特征系数
print(model.intercept_)  # 又名bias偏置,若设置为False，则为0
print(result)

[[109447.79646964  -6578.35485416]]
[340412.65957447]
[[356283.1103389]]


In [10]:
theta = np.hstack([np.array([model.intercept_]), model.coef_]).reshape(-1,1)
theta

array([[340412.65957447],
       [109447.79646964],
       [ -6578.35485416]])

In [11]:
# 这个结果似乎还是可以的,平均误差
# 这里的y的shape一定要是(,1),不然会广播计算
np.mean(np.abs(np.dot( np.hstack([ np.ones((x_train.shape[0],1)), x_train]) , theta) -y) / y)

0.15607399762704607

In [13]:
# 这个应该就是对模型的打分
model.score(x_train, y)

0.7329450180289141

In [12]:
linear_model.LinearRegression?

```py
Init signature: linear_model.LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None)
Docstring:     
Ordinary least squares Linear Regression.

Parameters
----------
fit_intercept : boolean, optional, default True
    whether to calculate the intercept for this model. If set
    to False, no intercept will be used in calculations
    (e.g. data is expected to be already centered).

normalize : boolean, optional, default False
    This parameter is ignored when ``fit_intercept`` is set to False.
    If True, the regressors X will be normalized before regression by
    subtracting the mean and dividing by the l2-norm.
    If you wish to standardize, please use
    :class:`sklearn.preprocessing.StandardScaler` before calling ``fit`` on
    an estimator with ``normalize=False``.

copy_X : boolean, optional, default True
    If True, X will be copied; else, it may be overwritten.

n_jobs : int or None, optional (default=None)
    The number of jobs to use for the computation. This will only provide
    speedup for n_targets > 1 and sufficient large problems.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.

Attributes
----------
coef_ : array, shape (n_features, ) or (n_targets, n_features)
    Estimated coefficients for the linear regression problem.
    If multiple targets are passed during the fit (y 2D), this
    is a 2D array of shape (n_targets, n_features), while if only
    one target is passed, this is a 1D array of length n_features.

intercept_ : array
    Independent term in the linear model.

Examples
--------
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression
>>> X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
>>> # y = 1 * x_0 + 2 * x_1 + 3
>>> y = np.dot(X, np.array([1, 2])) + 3
>>> reg = LinearRegression().fit(X, y)
>>> reg.score(X, y)
1.0
>>> reg.coef_
array([1., 2.])
>>> reg.intercept_ # doctest: +ELLIPSIS
3.0000...
>>> reg.predict(np.array([[3, 5]]))
array([16.])
```